// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace Attri.Runtime.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(17)
            {
                { typeof(global::Attri.Runtime.FrameData<float>), 0 },
                { typeof(global::Attri.Runtime.FrameData<int>), 1 },
                { typeof(global::Attri.Runtime.FrameData<string>), 2 },
                { typeof(global::Attri.Runtime.Value<float>), 3 },
                { typeof(global::Attri.Runtime.Value<float>[]), 4 },
                { typeof(global::Attri.Runtime.Value<int>), 5 },
                { typeof(global::Attri.Runtime.Value<int>[]), 6 },
                { typeof(global::Attri.Runtime.Value<string>), 7 },
                { typeof(global::Attri.Runtime.Value<string>[]), 8 },
                { typeof(global::Attri.Runtime.Value<ushort>[]), 9 },//workaround for error. overwrite T -> ushort
                { typeof(global::System.Collections.Generic.List<global::Attri.Runtime.FrameData<float>>), 10 },
                { typeof(global::System.Collections.Generic.List<global::Attri.Runtime.FrameData<int>>), 11 },
                { typeof(global::System.Collections.Generic.List<global::Attri.Runtime.FrameData<string>>), 12 },
                { typeof(global::Attri.Runtime.IAttribute), 13 },
                { typeof(global::Attri.Runtime.FloatAttribute), 14 },
                { typeof(global::Attri.Runtime.IntAttribute), 15 },
                { typeof(global::Attri.Runtime.StringAttribute), 16 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new Attri.Runtime.Formatters.Attri.Runtime.FrameDataFormatter<float>();
                case 1: return new Attri.Runtime.Formatters.Attri.Runtime.FrameDataFormatter<int>();
                case 2: return new Attri.Runtime.Formatters.Attri.Runtime.FrameDataFormatter<string>();
                case 3: return new Attri.Runtime.Formatters.Attri.Runtime.ValueFormatter<float>();
                case 4: return new global::MessagePack.Formatters.ArrayFormatter<global::Attri.Runtime.Value<float>>();
                case 5: return new Attri.Runtime.Formatters.Attri.Runtime.ValueFormatter<int>();
                case 6: return new global::MessagePack.Formatters.ArrayFormatter<global::Attri.Runtime.Value<int>>();
                case 7: return new Attri.Runtime.Formatters.Attri.Runtime.ValueFormatter<string>();
                case 8: return new global::MessagePack.Formatters.ArrayFormatter<global::Attri.Runtime.Value<string>>();
                case 9: return new global::MessagePack.Formatters.ArrayFormatter<global::Attri.Runtime.Value<ushort>>();//workaround for error. overwrite T -> ushort
                case 10: return new global::MessagePack.Formatters.ListFormatter<global::Attri.Runtime.FrameData<float>>();
                case 11: return new global::MessagePack.Formatters.ListFormatter<global::Attri.Runtime.FrameData<int>>();
                case 12: return new global::MessagePack.Formatters.ListFormatter<global::Attri.Runtime.FrameData<string>>();
                case 13: return new Attri.Runtime.Formatters.Attri.Runtime.IAttributeFormatter();
                case 14: return new Attri.Runtime.Formatters.Attri.Runtime.FloatAttributeFormatter();
                case 15: return new Attri.Runtime.Formatters.Attri.Runtime.IntAttributeFormatter();
                case 16: return new Attri.Runtime.Formatters.Attri.Runtime.StringAttributeFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
