// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace Attri.Runtime.Formatters.Attri.Runtime
{
    public sealed class AttributeAssetBaseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Attri.Runtime.AttributeAssetBase>
    {
        private readonly global::System.Collections.Generic.Dictionary<global::System.RuntimeTypeHandle, global::System.Collections.Generic.KeyValuePair<int, int>> typeToKeyAndJumpMap;
        private readonly global::System.Collections.Generic.Dictionary<int, int> keyToJumpMap;

        public AttributeAssetBaseFormatter()
        {
            this.typeToKeyAndJumpMap = new global::System.Collections.Generic.Dictionary<global::System.RuntimeTypeHandle, global::System.Collections.Generic.KeyValuePair<int, int>>(8, global::MessagePack.Internal.RuntimeTypeHandleEqualityComparer.Default)
            {
                { typeof(global::Attri.Runtime.IntegerAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(1, 0) },
                { typeof(global::Attri.Runtime.FloatAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(2, 1) },
                { typeof(global::Attri.Runtime.BoolAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(3, 2) },
                { typeof(global::Attri.Runtime.StringAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(4, 3) },
                { typeof(global::Attri.Runtime.Vector3AttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(5, 4) },
                { typeof(global::Attri.Runtime.Vector3IntAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(6, 5) },
                { typeof(global::Attri.Runtime.Vector2AttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(7, 6) },
                { typeof(global::Attri.Runtime.Vector2IntAttributeAssetBase).TypeHandle, new global::System.Collections.Generic.KeyValuePair<int, int>(8, 7) },
            };
            this.keyToJumpMap = new global::System.Collections.Generic.Dictionary<int, int>(8)
            {
                { 1, 0 },
                { 2, 1 },
                { 3, 2 },
                { 4, 3 },
                { 5, 4 },
                { 6, 5 },
                { 7, 6 },
                { 8, 7 },
            };
        }

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Attri.Runtime.AttributeAssetBase value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::System.Collections.Generic.KeyValuePair<int, int> keyValuePair;
            if (value != null && this.typeToKeyAndJumpMap.TryGetValue(value.GetType().TypeHandle, out keyValuePair))
            {
                writer.WriteArrayHeader(2);
                writer.WriteInt32(keyValuePair.Key);
                switch (keyValuePair.Value)
                {
                    case 0:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.IntegerAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.IntegerAttributeAssetBase)value, options);
                        break;
                    case 1:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.FloatAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.FloatAttributeAssetBase)value, options);
                        break;
                    case 2:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.BoolAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.BoolAttributeAssetBase)value, options);
                        break;
                    case 3:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.StringAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.StringAttributeAssetBase)value, options);
                        break;
                    case 4:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector3AttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.Vector3AttributeAssetBase)value, options);
                        break;
                    case 5:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector3IntAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.Vector3IntAttributeAssetBase)value, options);
                        break;
                    case 6:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector2AttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.Vector2AttributeAssetBase)value, options);
                        break;
                    case 7:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector2IntAttributeAssetBase>(options.Resolver).Serialize(ref writer, (global::Attri.Runtime.Vector2IntAttributeAssetBase)value, options);
                        break;
                    default:
                        break;
                }

                return;
            }

            writer.WriteNil();
        }

        public global::Attri.Runtime.AttributeAssetBase Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            if (reader.ReadArrayHeader() != 2)
            {
                throw new global::System.InvalidOperationException("Invalid Union data was detected. Type:global::Attri.Runtime.AttributeAssetBase");
            }

            options.Security.DepthStep(ref reader);
            var key = reader.ReadInt32();

            if (!this.keyToJumpMap.TryGetValue(key, out key))
            {
                key = -1;
            }

            global::Attri.Runtime.AttributeAssetBase result = null;
            switch (key)
            {
                case 0:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.IntegerAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 1:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.FloatAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 2:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.BoolAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 3:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.StringAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 4:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector3AttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 5:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector3IntAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 6:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector2AttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                case 7:
                    result = (global::Attri.Runtime.AttributeAssetBase)global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Attri.Runtime.Vector2IntAttributeAssetBase>(options.Resolver).Deserialize(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }

            reader.Depth--;
            return result;
        }
    }


}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
