@startjson
[
    {
        "Name" : "P",
        "Type" : "Real",
        "Dimension" : "3",
        "Value" : ["csv as value"]
    },
    {
        "Name" : "uv",
        "Type" : "Real",
        "Dimension" : "2",
        "Value" : ["csv as value"]
    },
    {
        "Name" : "N",
        "Type" : "Real",
        "Dimension" : "3",
        "Value" : ["csv as value"]
    }
]
@endjson
